[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.98.0",
    "crewai-tools>=0.32.1",
    "python-dotenv>=1.0.1",
]
